# Estados de la orden
ORDER_STATUS_PENDING = 'PENDING'
ORDER_STATUS_CONFIRMED = 'CONFIRMED'
ORDER_STATUS_PROCESSING = 'PROCESSING'
ORDER_STATUS_SHIPPED = 'SHIPPED'
ORDER_STATUS_DELIVERED = 'DELIVERED'
ORDER_STATUS_CANCELLED = 'CANCELLED'

# Estados que permiten cancelacion
CANCELLABLE_STATUSES = [ORDER_STATUS_PENDING, ORDER_STATUS_CONFIRMED]

# Cache timeouts
ORDER_CACHE_TIMEOUT = 300  # 5 minutos
ORDER_LIST_CACHE_TIMEOUT = 60  # 1 minuto
