# Generated by Django 6.0.6 on 2026-06-08 07:27

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Clave de sesion para carritos '
                                                                                      'anonimos.', max_length=40,
                                                 null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuario propietario del carrito. Null para carritos '
                                                                 'anonimos.', null=True,
                                           on_delete=django.db.models.deletion.CASCADE, related_name='carts',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Cantidad del producto. Minimo 1.',
                                                         validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de agregar '
                                                                               'al carrito.', max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(help_text='Carrito al que pertenece este item.',
                                           on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                           to='cart.cart')),
                ('product', models.ForeignKey(help_text='Producto referenciado en este item del carrito.',
                                              on_delete=django.db.models.deletion.PROTECT, related_name='cart_items',
                                              to='products.product')),
            ],
            options={
                'db_table': 'cart_cartitem',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user',),
                                               name='uniq_cart_per_user'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)),
                                               fields=('session_key',), name='uniq_cart_per_session'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='idx_cartitem_cart_product'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
