# Generated by Django 6.0.6 on 2026-06-08 07:27

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(
                    choices=[('PENDING', 'Pendiente'), ('CONFIRMED', 'Confirmada'), ('PROCESSING', 'En proceso'),
                             ('SHIPPED', 'Enviada'), ('DELIVERED', 'Entregada'), ('CANCELLED', 'Cancelada')],
                    db_index=True, default='PENDING', help_text='Estado actual de la orden.', max_length=20)),
                ('total_amount',
                 models.DecimalField(decimal_places=2, default=0, help_text='Monto total de la orden.', max_digits=12)),
                ('notes', models.TextField(blank=True, default='', help_text='Notas adicionales sobre la orden.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Usuario que realizo la orden.',
                                           on_delete=django.db.models.deletion.PROTECT, related_name='orders',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name',
                 models.CharField(help_text='Nombre del producto al momento de la compra.', max_length=255)),
                ('product_sku', models.CharField(help_text='SKU del producto al momento de la compra.', max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='Cantidad comprada.',
                                                         validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price',
                 models.DecimalField(decimal_places=2, help_text='Precio unitario al momento de la compra.',
                                     max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del item (precio * cantidad).',
                                                 max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(help_text='Orden a la que pertenece este item.',
                                            on_delete=django.db.models.deletion.CASCADE, related_name='items',
                                            to='orders.order')),
                ('product',
                 models.ForeignKey(help_text='Producto original (puede ser null si el producto fue eliminado).',
                                   null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items',
                                   to='products.product')),
            ],
            options={
                'db_table': 'orders_orderitem',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='idx_order_user_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='idx_order_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='idx_order_created'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='idx_orderitem_order'),
        ),
    ]
