# Generated by Django 6.0.6 on 2026-06-08 07:27

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False,
                                        help_text='Identificador publico unico del producto.', primary_key=True,
                                        serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Nombre del producto. Maximo 255 caracteres.',
                                          max_length=255)),
                ('description',
                 models.TextField(blank=True, default='', help_text='Descripcion detallada del producto.')),
                ('price',
                 models.DecimalField(decimal_places=2, help_text='Precio unitario del producto. Debe ser mayor a 0.',
                                     max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('sku', models.CharField(db_index=True,
                                         help_text='Codigo unico de inventario. Solo mayusculas, numeros y guiones.',
                                         max_length=50, unique=True, validators=[
                        django.core.validators.RegexValidator(code='invalid_sku',
                                                              message='SKU debe contener solo letras mayusculas, numeros y guiones.',
                                                              regex='^[A-Z0-9\\-]+$')])),
                ('stock', models.PositiveIntegerField(default=0, help_text='Cantidad disponible en inventario.',
                                                      validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True,
                                                  help_text='Indica si el producto esta activo y disponible para la venta.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products_product',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='idx_product_name'),
                            models.Index(fields=['sku'], name='idx_product_sku'),
                            models.Index(fields=['is_active', 'created_at'], name='idx_product_active_created'),
                            models.Index(fields=['price'], name='idx_product_price')],
                'constraints': [models.CheckConstraint(condition=models.Q(('stock__gte', 0)),
                                                       name='chk_product_stock_non_negative')],
            },
        ),
    ]
