# Generated by Django 6.0.6 on 2026-06-08 17:33

from django.db import migrations, models

import products.models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True,
                                    help_text='Imagen principal del producto. Formatos permitidos: JPG, PNG, WEBP. Tamano maximo: 2MB.',
                                    null=True, upload_to=products.models.product_image_upload_path),
        ),
    ]
